# Generated by Django 5.0.7 on 2024-08-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lecture',
            new_name='Supervisor',
        ),
    ]
