# Generated by Django 5.0.7 on 2024-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_rename_lecture_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
