# Generated by Django 5.0.7 on 2024-08-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_supervisor_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notText', models.TextField()),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.supervisor')),
            ],
        ),
    ]
