# Generated by Django 5.0.7 on 2024-07-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('other_names', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRolesApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('studentId', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=8)),
                ('approval', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.roledetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name_plural': 'Student Roles Applied',
            },
        ),
    ]
