# Generated by Django 5.0.7 on 2024-07-24 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_roledetail_company'),
        ('student', '0002_alter_studentrolesapplied_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='company',
        ),
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='studentId',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentrolesapplied',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roles_applied', to='manager.roledetail'),
        ),
    ]
