# Generated by Django 5.0.7 on 2024-07-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_roledetail_company'),
        ('student', '0005_student_level_student_programme_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studentrolesapplied',
            name='status',
        ),
        migrations.AddField(
            model_name='studentrolesapplied',
            name='applicationFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='StudentAcceptedRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], max_length=12)),
                ('smallInfo', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_data', models.DateField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_accepted_roles', to='manager.roledetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name_plural': 'Student Roles Applied',
            },
        ),
    ]
