# Generated by Django 5.0.7 on 2024-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentrolesapplied_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrolesapplied',
            name='applicatonDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
