# Generated by Django 5.0.7 on 2024-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentrolesapplied_applicatondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrolesapplied',
            name='applicatonDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
