# Generated by Django 5.0.7 on 2024-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentinternship_delete_studentacceptedroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinternship',
            name='optionalFile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
