# Generated by Django 5.0.7 on 2024-08-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_roledetail_company'),
        ('student', '0013_alter_studentappliedinternship_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInternship',
            new_name='StudentsInternshipsOn',
        ),
    ]
