# Generated by Django 5.0.7 on 2024-08-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_roledetail_company'),
        ('student', '0014_rename_studentinternship_studentsinternshipson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsInternshipsOn',
            new_name='StudentInternships',
        ),
    ]
