# Generated by Django 5.0.7 on 2024-08-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_rename_manager_managernotification_company'),
        ('student', '0016_studentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinternships',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
    ]
