# Generated by Django 5.0.7 on 2024-08-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_manager_password'),
        ('student', '0017_studentinternships_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='student.student')),
                ('email', models.CharField(max_length=150)),
                ('durationOfInternship', models.CharField(blank=True, max_length=150, null=True)),
                ('qualityOfWork', models.CharField(max_length=150)),
                ('abilityToWork', models.CharField(max_length=150)),
                ('initiativeAndCreativity', models.CharField(max_length=150)),
                ('characterTraits', models.CharField(max_length=150)),
                ('dependabilty', models.CharField(max_length=150)),
                ('attendanceAndPunctuality', models.CharField(max_length=150)),
                ('organizationalFit', models.CharField(max_length=150)),
                ('responseToSupervision', models.CharField(max_length=150)),
                ('suggestionsForImprovement', models.TextField()),
                ('nameOfSupervisor', models.CharField(max_length=150)),
                ('positionOfSupervisor', models.CharField(blank=True, max_length=150, null=True)),
                ('supervisorEmail', models.CharField(blank=True, max_length=150, null=True)),
                ('supervisorContact', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
    ]
