# Generated by Django 5.0.7 on 2024-08-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_managerprofilechange'),
        ('student', '0019_alter_studentassessment_suggestionsforimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrolesapplied',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
    ]
