# Generated by Django 5.0.7 on 2024-08-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_studentrolesapplied_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='student_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
