# Generated by Django 5.0.7 on 2024-07-15 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('briefInfo', models.TextField()),
                ('contractStatus', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], max_length=8)),
                ('reportStatus', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('numberOfInterns', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
    ]
