# Generated by Django 5.0.7 on 2024-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='contractStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified')], max_length=8),
        ),
        migrations.AlterField(
            model_name='manager',
            name='reportStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified')], max_length=8),
        ),
    ]
