# Generated by Django 5.0.7 on 2024-07-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_contractstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='durationOfExistence',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
