# Generated by Django 5.0.7 on 2024-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_manager_durationofexistence'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledetail',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
