# Generated by Django 5.0.7 on 2024-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_roledetail_moreinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='companyLogo',
            field=models.ImageField(null=True, upload_to='company_logos/'),
        ),
    ]
