# Generated by Django 5.0.7 on 2024-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_manager_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='companyLogo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
