# Generated by Django 5.0.7 on 2024-07-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_manager_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetail',
            name='moreInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
