# Generated by Django 5.0.7 on 2024-07-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_roledetail_moreinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetail',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
