# Generated by Django 5.0.7 on 2024-07-24 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_roledetail_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_vacancies', to='manager.manager'),
        ),
    ]
