# Generated by Django 5.0.7 on 2024-08-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_rename_manager_managernotification_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='companyCertificate',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
