# Generated by Django 5.0.7 on 2024-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_manager_companycertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
