# Generated by Django 5.0.7 on 2024-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_managerprofilechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegistered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
